<?php

use Illuminate\Database\Seeder;

class DosenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $password = "123";
        $password = bcrypt($password);

        $dosen=[ ['id'=>'1',
                  'name'=>'Lisana, S.Kom., M.Inf.Tech.',
                  'npk'=>'199013',
                  'password'=>$password,
                  'photo'=>'',
                  'acceptKP'=>'1',
                  'acceptTA'=>'1',
                  'isActive'=>'1'],

        	     ['id'=>'2',
                  'name'=>'Tyrza Adelia, S.Sn., M.Inf.Tech.',
                  'npk'=>'210134',
                  'password'=>$password,
                  'photo'=>'',
                  'acceptKP'=>'0',
                  'acceptTA'=>'0',
                  'isActive'=>'1',],
               ['id'=>'3',
                  'name'=>'Melissa Angga, S.T., M.M.Comp.',
                  'npk'=>'200046',
                  'password'=>$password,
                  'photo'=>'',
                  'acceptKP'=>'1',
                  'acceptTA'=>'1',
                  'isActive'=>'1',],
               ['id'=>'4',
                  'name'=>'Dhiani Tresna Absari, S.T., M.Kom.',
                  'npk'=>'202017',
                  'password'=>$password,
                  'photo'=>'',
                  'acceptKP'=>'0',
                  'acceptTA'=>'1',
                  'isActive'=>'1',],
               ['id'=>'5',
                  'name'=>'Ir. Bambang Prijambodo, M.MT.',
                  'npk'=>'187018',
                  'password'=>$password,
                  'photo'=>'',
                  'acceptKP'=>'1',
                  'acceptTA'=>'1',
                  'isActive'=>'1',],
              ['id'=>'6',
                  'name'=>'Susana Limanto, S.T., M.Si.',
                  'npk'=>'197030',
                  'password'=>$password,
                  'photo'=>'',
                  'acceptKP'=>'1',
                  'acceptTA'=>'1',
                  'isActive'=>'1',],
              ['id'=>'7',
                  'name'=>'Prof. Drs. Nur Iriawan, M.Kom., Ph.D.',
                  'npk'=>'205720',
                  'password'=>$password,
                  'photo'=>'',
                  'acceptKP'=>'1',
                  'acceptTA'=>'1',
                  'isActive'=>'1',],
            ['id'=>'8',
                  'name'=>'Dr. Budi Hartanto, S.T., M.Sc.',
                  'npk'=>'195012',
                  'password'=>$password,
                  'photo'=>'',
                  'acceptKP'=>'1',
                  'acceptTA'=>'1',
                  'isActive'=>'1',],
             ['id'=>'9',
                  'name'=>'Maya Hilda Lestari Louk, S.T., M.Sc.',
                  'npk'=>'215027',
                  'password'=>$password,
                  'photo'=>'',
                  'acceptKP'=>'0',
                  'acceptTA'=>'0',
                  'isActive'=>'1',],
              ['id'=>'10',
                  'name'=>'Dr. Joko Siswantoro, S.Si., M.Si.',
                  'npk'=>'198032',
                  'password'=>$password,
                  'photo'=>'',
                  'acceptKP'=>'1',
                  'acceptTA'=>'0',
                  'isActive'=>'1',],   
              ['id'=>'11',
                  'name'=>'Njoto Benarkah, S.T., M.Sc.',
                  'npk'=>'201026',
                  'password'=>$password,
                  'photo'=>'',
                  'acceptKP'=>'0',
                  'acceptTA'=>'1',
                  'isActive'=>'1',],  
              ['id'=>'12',
                  'name'=>'Endah Asmawati, S.Si., M.Si.',
                  'npk'=>'201007',
                  'password'=>$password,
                  'photo'=>'',
                  'acceptKP'=>'1',
                  'acceptTA'=>'1',
                  'isActive'=>'1',], 
              ['id'=>'13',
                  'name'=>'Ellysa Tjandra, S.T., M.MT.',
                  'npk'=>'  203014',
                  'password'=>$password,
                  'photo'=>'',
                  'acceptKP'=>'1',
                  'acceptTA'=>'0',
                  'isActive'=>'1',], 
              ['id'=>'14',
                  'name'=>'Mohammad Farid Naufal, S.Kom., M.Kom.',
                  'npk'=>'216037',
                  'password'=>$password,
                  'photo'=>'',
                  'acceptKP'=>'1',
                  'acceptTA'=>'0',
                  'isActive'=>'1',], 
              ['id'=>'15',
                  'name'=>'Hendra Dinata, S.T., M.Kom.',
                  'npk'=>'210034',
                  'password'=>$password,
                  'photo'=>'',
                  'acceptKP'=>'0',
                  'acceptTA'=>'1',
                  'isActive'=>'1',], 
              ['id'=>'16',
                  'name'=>'Richard Pramono, S.Kom., M.Sc.',
                  'npk'=>'209023',
                  'password'=>$password,
                  'photo'=>'',
                  'acceptKP'=>'0',
                  'acceptTA'=>'1',
                  'isActive'=>'1',], 
              ['id'=>'17',
                  'name'=>'Andre, S.T., M.Sc.',
                  'npk'=>'208020',
                  'password'=>$password,
                  'photo'=>'',
                  'acceptKP'=>'1',
                  'acceptTA'=>'1',
                  'isActive'=>'1',], 
              ['id'=>'18',
                  'name'=>'Monica Widiasri, S.Kom., M.Kom.',
                  'npk'=>'204027',
                  'password'=>$password,
                  'photo'=>'',
                  'acceptKP'=>'1',
                  'acceptTA'=>'1',
                  'isActive'=>'1',], 
              ['id'=>'19',
                  'name'=>'Liliana, S.T., M.MSI.',
                  'npk'=>'206020',
                  'password'=>$password,
                  'photo'=>'',
                  'acceptKP'=>'1',
                  'acceptTA'=>'1',
                  'isActive'=>'1',], 
              ['id'=>'20',
                  'name'=>'Daniel Soesanto, S.T., M.M',
                  'npk'=>'209344',
                  'password'=>$password,
                  'photo'=>'',
                  'acceptKP'=>'1',
                  'acceptTA'=>'1',
                  'isActive'=>'1',]


        ];
        DB::table('dosen')->insert($dosen);
    }
}
