<?php

use Illuminate\Database\Seeder;

class MahasiswaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $password = "123";
        $password = bcrypt($password);
        
        $mahasiswa=[ ['id'=>'1',
                          'nrp'=>'160401',
                          'name'=>'Evin Cintiawan',
                          'password'=>$password,
                          'photo'=>'',
                          'isActive'=>'1'],
        	         ['id'=>'2',
                         'nrp'=>'160402',
                         'name'=>'Robby Ongko Wijoyo',
                         'password'=>$password,
                         'photo'=>'',
                         'isActive'=>'1'],
        	        ['id'=>'3',
                        'nrp'=>'160403',
                        'name'=>'Rama Adhiguna',
                        'password'=>$password,
                        'photo'=>'',
                        'isActive'=>'1'],
        	        ['id'=>'4',
                         'nrp'=>'160404',
                         'name'=>'Lucas Leonard',
                         'password'=>$password,
                         'photo'=>'',
                         'isActive'=>'1'],
                    ['id'=>'5',
                         'nrp'=>'160405',
                         'name'=>'Billie Arianto',
                         'password'=>$password,
                         'photo'=>'',
                         'isActive'=>'1'],
                    ['id'=>'6',
                         'nrp'=>'160406',
                         'name'=>'Sonny Haryadi',
                         'password'=>$password,
                         'photo'=>'',
                         'isActive'=>'1'],
                    ['id'=>'7',
                         'nrp'=>'160407',
                         'name'=>'Kevin Andryano',
                         'password'=>$password,
                         'photo'=>'',
                         'isActive'=>'1'],
                     ['id'=>'8',
                         'nrp'=>'160408',
                         'name'=>'Faishal Hendaryawan',
                         'password'=>$password,
                         'photo'=>'',
                         'isActive'=>'1'],
                     ['id'=>'9',
                         'nrp'=>'160409',
                         'name'=>'Putu Aditya Riva',
                         'password'=>$password,
                         'photo'=>'',
                         'isActive'=>'1'],
                     ['id'=>'10',
                         'nrp'=>'160410',
                         'name'=>'Fadhil Amadan',
                         'password'=>$password,
                         'photo'=>'',
                         'isActive'=>'0'],
                     ['id'=>'11',
                         'nrp'=>'160411',
                         'name'=>'Indy Quorrotu Ayuni',
                         'password'=>$password,
                         'photo'=>'',
                         'isActive'=>'0'],
                    ['id'=>'12',
                         'nrp'=>'160412',
                         'name'=>'Yudisthira Rahmat',
                         'password'=>$password,
                         'photo'=>'',
                         'isActive'=>'1'],
                    ['id'=>'13',
                         'nrp'=>'160413',
                         'name'=>'Yunitasari Ernomo',
                         'password'=>$password,
                         'photo'=>'',
                         'isActive'=>'1'],
                    
                    ['id'=>'14',
                         'nrp'=>'160414',
                         'name'=>'Indah Permatasari',
                         'password'=>$password,
                         'photo'=>'',
                         'isActive'=>'1'],
                    ['id'=>'15',
                         'nrp'=>'160415',
                         'name'=>'Man Jefri Sanjaya',
                         'password'=>$password,
                         'photo'=>'',
                         'isActive'=>'1'],
                    ['id'=>'16',
                         'nrp'=>'160416',
                         'name'=>'Tandry Leonardo',
                         'password'=>$password,
                         'photo'=>'',
                         'isActive'=>'1'],
                    ['id'=>'17',
                         'nrp'=>'160417',
                         'name'=>'Aulia Rahman',
                         'password'=>$password,
                         'photo'=>'',
                         'isActive'=>'1'],
                    ['id'=>'18',
                         'nrp'=>'160418',
                         'name'=>'Andra Hadi Wijaya',
                         'password'=>$password,
                         'photo'=>'',
                         'isActive'=>'0'],
                    ['id'=>'19',
                         'nrp'=>'160419',
                         'name'=>'Agnes Fransisca',
                         'password'=>$password,
                         'photo'=>'',
                         'isActive'=>'1']
                    
        ];
        DB::table('mahasiswa')->insert($mahasiswa);
    }
}
