<?php

use Illuminate\Database\Seeder;

class SlotSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        /*$slot=[ ['id'=>'1',
                     'date'=>'2017-05-10',
                     'start'=>'10:00:00',
                     'end'=>'10:30:00',
                     'place'=>'Pabrik Cokelat',
                     'isRequest'=>'0',
                     'status'=>'Waiting',
                     'mahasiswa_id'=>'1',
                     'dosen_id'=>'1',
                     'jenis_konsul_id'=>'1'],
        	    ['id'=>'2',
                    'date'=>'2017-05-10',
                    'start'=>'10:31:00',
                    'end'=>'11:00:00',
                    'place'=>'Pabrik Tisu',
                    'isRequest'=>'0',
                    'status'=>'Waiting',
                    'mahasiswa_id'=>'2',
                    'dosen_id'=>'3',
                    'jenis_konsul_id'=>'2'],
                ['id'=>'3',
                    'date'=>'2017-05-11',
                    'start'=>'08:30:00',
                    'end'=>'09:00:00',
                    'place'=>'Perusahan Home Hardware',
                    'isRequest'=>'0',
                    'status'=>'Waiting',
                    'mahasiswa_id'=>'3',
                    'dosen_id'=>'5',
                    'jenis_konsul_id'=>'1'],
                ['id'=>'4',
                    'date'=>'2017-06-09',
                    'start'=>'08:30:00',
                    'end'=>'09:00:00',
                    'place'=>'Perusahan Home Hardware',
                    'isRequest'=>'0',
                    'status'=>'Waiting',
                    'mahasiswa_id'=>'4',
                    'dosen_id'=>'6',
                    'jenis_konsul_id'=>'3'],
                ['id'=>'5',
                    'date'=>'2017-06-09',
                    'start'=>'09:31:00',
                    'end'=>'10:00:00',
                    'place'=>'Perusahan Home Software',
                    'isRequest'=>'0',
                    'status'=>'Waiting',
                    'mahasiswa_id'=>'5',
                    'dosen_id'=>'7',
                    'jenis_konsul_id'=>'1'],
                ['id'=>'6',
                    'date'=>'2017-08-22',
                    'start'=>'09:30:00',
                    'end'=>'10:00:00',
                    'place'=>'Pabrik Elektronik',
                    'isRequest'=>'0',
                    'status'=>'Waiting',
                    'mahasiswa_id'=>'6',
                    'dosen_id'=>'8',
                    'jenis_konsul_id'=>'3'],
                ['id'=>'7',
                    'date'=>'2017-08-22',
                    'start'=>'10:01:00',
                    'end'=>'10:30:00',
                    'place'=>'Pabrik Recycle',
                    'isRequest'=>'0',
                    'status'=>'Waiting',
                    'mahasiswa_id'=>'12',
                    'dosen_id'=>'12',
                    'jenis_konsul_id'=>'2'],
                ['id'=>'8',
                    'date'=>'2017-08-22',
                    'start'=>'10:31:00',
                    'end'=>'11:00:00',
                    'place'=>'Pabrik Smartphone',
                    'isRequest'=>'0',
                    'status'=>'Waiting',
                    'mahasiswa_id'=>'13',
                    'dosen_id'=>'17',
                    'jenis_konsul_id'=>'1'],
                ['id'=>'9',
                    'date'=>'2017-05-10',
                    'start'=>'11:01:00',
                    'end'=>'11:30:00',
                    'place'=>'Pabrik Lem',
                    'isRequest'=>'0',
                    'status'=>'Waiting',
                    'mahasiswa_id'=>'14',
                    'dosen_id'=>'17',
                    'jenis_konsul_id'=>'1'],
                ['id'=>'10',
                    'date'=>'2017-05-10',
                    'start'=>'11:31:00',
                    'end'=>'12:00:00',
                    'place'=>'Perusahaan Informasi',
                    'isRequest'=>'0',
                    'status'=>'Waiting',
                    'mahasiswa_id'=>'19',
                    'dosen_id'=>'12',
                    'jenis_konsul_id'=>'1']
        ];
        DB::table('slot')->insert($slot);*/
    }
}
